// Creates list of words //
var listOfWords = [
    'jazzed',
    'quiz',
    'babe',
    'jinx',
    'buzzer',
    'jive',
    'joking',
    'yammering',
    'beekeeper',
    'chihuahua',
    'heeler',
    'zipper',
    'babbling',
    'parallaxes',
    'fulfilling',
    'bubbliest',
    'quaking',
    'skydiving',
    'jagged',
    'foxes',
    'onomatopoeia',
    'puppy',
    'jaywalking',
    'kookiness',
    'lackadaisical',
    'discombobulate',
    'curmudgeon',
    'flummox',
    'woebegone',
    'hullaballoo',
    'ragamuffin',
    'whippersnapper',
    'gobbledygook',
    'gibberish',
    'aristotle'
  ];
  // Exports the list of words to other scripts //
  module.exports = listOfWords;
